WIP add bash functions for debian building automation. not fully refactored dregs of globalvariables

diff --git a/automation/bash_functions b/automation/bash_functions
--- a/automation/bash_functions
+++ b/automation/bash_functions
@@ -124,3 +124,80 @@ _print_banner() {
     echo
 }
 
+_build_tarball () {
+    DEB_BUILD_ROOT=$1
+    src_pkgname=$2
+    vernum=$3
+    SRC=$4
+    FILES=$5
+    _eif=${6-0} # exit if failed
+    if [ ! -e ${SRC} ]; then
+        if [ $_eif != 0 ]; then
+            _exit_if_failed 127 "FAILED: directory not found: $SRC"
+        fi
+        echo "FAILED: directory not found: $SRC";
+        return 127;
+    fi
+    src_pkgname_ver=${src_pkgname}-${vernum}
+    src_pkgname_orig_directory=${src_pkgname_ver}
+    fn_ver=${src_pkgname}_${vernum}
+    DEB_BUILD_PKG=${DEB_BUILD_ROOT}/${src_pkgname}/
+    DEB_BUILD=${DEB_BUILD_PKG}/${src_pkgname}/${src_pkgname_orig_directory}
+    if [ $DEBUG_DEB == 0 ]; then
+        if [ -e ${DEB_BUILD} ]; then
+            echo "OK?: Found existing directory $DEB_BUILD ; Assuming this is already built";
+            return 0;
+        fi
+    fi
+    mkdir -p ${DEB_BUILD_PKG}
+    rm -rf ${DEB_BUILD_PKG}/*
+    mkdir -p ${DEB_BUILD}
+    cd ${SRC}
+    cp -Rf ${FILES} ${DEB_BUILD}/
+    cd ${DEB_BUILD}
+    # ls -a
+    cd ${DEB_BUILD}/..
+    tar -zcvf ${fn_ver}.orig.tar.gz ${src_pkgname_orig_directory}
+    cd ${DEB_BUILD}
+    debuild -us -uc 
+    if [ $? == 0 ]; then
+        echo "OK: built $src_pkgname";
+        return 0;
+    else
+        echo "FAILED to build deb package $src_pkgname";
+        cd ${SRC}
+        if [ $DEBUG_DEB == 0 ]; then
+            rm -rf ${DEB_BUILD_PKG}/*
+        else
+            echo "DEBUG active: leaving directory $DEB_BUILD_PKG";
+        fi
+        if [ $_eif != 0 ]; then
+            _exit_if_failed 1 "FAILED to build deb package $src_pkgname"
+        fi
+    fi
+}
+
+_checked_build_tarball () {
+    _build_tarball $1 $2 $3 "$4";
+    ret_code=$?
+    if [ ! $? == 0 ]; then
+        exit 1;
+    else
+        echo "OK: copying to ${DEB_PKGS_DIR}";
+        cp ${DEB_BUILD}/../*.deb ${DEB_PKGS_DIR}/ ;
+    fi
+}
+
+
+_install_deb() {
+    libname=$1
+    deb_version=$2
+    # dpkg -c ${DEB_PKGS_DIR}/lib${src_pkgname}-dev_${deb_version}_amd64.deb
+    ${SUDOCMD} dpkg -i ${DEB_PKGS_DIR}/${libname}_${deb_version}_amd64.deb
+    if [ ! $? == 0 ]; then
+        echo "FAILED: installing ${libname}";
+        exit 1;
+    fi
+}
+
+
